# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Enterprise' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Enterprise

pod "TPKeyboardAvoidingSwift"
pod 'SVProgressHUD'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'MagicalRecord'
pod 'Cosmos', '~> 17.0'
#pod 'IQKeyboardManagerSwift'
pod 'SkyFloatingLabelTextField', '~> 3.0'
pod 'MaterialComponents/Buttons'
  target 'EnterpriseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EnterpriseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
